printf ".ber\n"
valgrind ../so_long .ber 2>&1 | grep -i "error summary"
printf "\nsubject_map.ber\n"
valgrind ../so_long subject_map.ber 2>&1 | grep -i "error summary"
printf "\nsubject_map2.ber\n"
valgrind ../so_long subject_map2.ber 2>&1 | grep -i "error summary"
printf "\ntestmap\n"
valgrind ../so_long testmap 2>&1 | grep -i "error summary"
printf "\ntestmap_breached.ber\n"
valgrind ../so_long testmap_breached.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_maxsize.ber\n"
valgrind ../so_long testmap_maxsize.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_maze_full_coll.ber\n"
valgrind ../so_long testmap_maze_full_coll.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_noaccessible_collectible.ber\n"
valgrind ../so_long testmap_noaccessible_collectible.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_noaccessible_exit.ber\n"
valgrind ../so_long testmap_noaccessible_exit.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_nocollectible.ber\n"
valgrind ../so_long testmap_nocollectible.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_noexit.ber\n"
valgrind ../so_long testmap_noexit.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_noplayer.ber\n"
valgrind ../so_long testmap_noplayer.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_norectangle.ber\n"
valgrind ../so_long testmap_norectangle.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_notamap.ber\n"
valgrind ../so_long testmap_notamap.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_nothing.ber\n"
valgrind ../so_long testmap_nothing.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_nowall.ber\n"
valgrind ../so_long testmap_nowall.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_onecol.ber\n"
valgrind ../so_long testmap_onecol.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_oneline.ber\n"
valgrind ../so_long testmap_oneline.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_toobig_firstlineok.ber\n"
valgrind ../so_long testmap_toobig_firstlineok.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_toobig.ber\n"
valgrind ../so_long testmap_toobig.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_toomuch_lines.ber\n"
valgrind ../so_long testmap_toomuch_lines.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_two_exits.ber\n"
valgrind ../so_long testmap_two_exits.ber 2>&1 | grep -i "error summary"
printf "\ntestmap_two_players.ber\n"
valgrind ../so_long testmap_two_players.ber 2>&1 | grep -i "error summary"
printf "\ntestmap.be\n"
valgrind ../so_long testmap.be 2>&1 | grep -i "error summary"
printf "\ntestmap.ber\n"
valgrind ../so_long testmap.ber 2>&1 | grep -i "error summary"
printf "\ntestmap.berr\n"
valgrind ../so_long testmap.berr 2>&1 | grep -i "error summary"
printf "\ntestmap.txt\n"
valgrind ../so_long testmap.txt 2>&1 | grep -i "error summary"
